module.exports = {
  apps: [
    {
      name: "alerts-dashboard",
      script: "npx",
      args: "next start -p 3000",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/alerts-dashboard-error.log",
      out_file: "./logs/alerts-dashboard-out.log",
      log_file: "./logs/alerts-dashboard-combined.log",
      time: true,
    },
    {
      name: "binance-worker",
      script: "workers/binance-worker.js",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/binance-worker-error.log",
      out_file: "./logs/binance-worker-out.log",
      log_file: "./logs/binance-worker-combined.log",
      time: true,
    },
    {
      name: "alert-worker",
      script: "workers/alert-worker.js",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
      },
      error_file: "./logs/alert-worker-error.log",
      out_file: "./logs/alert-worker-out.log",
      log_file: "./logs/alert-worker-combined.log",
      time: true,
    },
    {
      name: "cleanup-worker",
      script: "workers/cleanup-worker.js",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "200M",
      env: {
        NODE_ENV: "production",
        CLEANUP_WORKER_AUTOSTART: "true",
      },
      error_file: "./logs/cleanup-worker-error.log",
      out_file: "./logs/cleanup-worker-out.log",
      log_file: "./logs/cleanup-worker-combined.log",
      time: true,
    },
  ],
};
