module.exports = {
  apps: [
    {
      name: "alerts-dashboard",
      script: "node_modules/.bin/next",
      args: "start -p 3000",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_file: ".env",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "./logs/alerts-dashboard-error.log",
      out_file: "./logs/alerts-dashboard-out.log",
      log_file: "./logs/alerts-dashboard-combined.log",
      time: true,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "binance-worker",
      script: "workers/binance-worker.js",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env_file: ".env.local",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        MONGODB_URI: "mongodb://localhost:27017/crypto-alerts",
      },
      error_file: "./logs/binance-worker-error.log",
      out_file: "./logs/binance-worker-out.log",
      log_file: "./logs/binance-worker-combined.log",
      time: true,
    },
    {
      name: "alert-worker",
      script: "workers/alert-worker.js",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env_file: ".env",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        MONGODB_URI: "mongodb://localhost:27017/crypto-alerts",
      },
      error_file: "./logs/alert-worker-error.log",
      out_file: "./logs/alert-worker-out.log",
      log_file: "./logs/alert-worker-combined.log",
      time: true,
    },
    {
      name: "cleanup-worker",
      script: "workers/cleanup-worker.js",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "200M",
      env: {
        NODE_ENV: "production",
        CLEANUP_WORKER_AUTOSTART: "true",
      },
      error_file: "./logs/cleanup-worker-error.log",
      out_file: "./logs/cleanup-worker-out.log",
      log_file: "./logs/cleanup-worker-combined.log",
      time: true,
    },
    {
      name: "notify-worker",
      script: "workers/notify-worker.js",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env_file: ".env",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        MONGODB_URI: "mongodb://localhost:27017/crypto-alerts",
      },
      error_file: "./logs/notify-worker-error.log",
      out_file: "./logs/notify-worker-out.log",
      log_file: "./logs/notify-worker-combined.log",
      time: true,
    },
    {
      name: "db-queue-worker",
      script: "workers/db-queue-worker.js",
      cwd: "/var/www/alerts-dashboard",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env_file: ".env",
      env: {
        NODE_ENV: "production",
        REDIS_HOST: "localhost",
        REDIS_PORT: 6379,
        MONGODB_URI: "mongodb://localhost:27017/crypto-alerts",
      },
      error_file: "./logs/db-queue-worker-error.log",
      out_file: "./logs/db-queue-worker-out.log",
      log_file: "./logs/db-queue-worker-combined.log",
      time: true,
    },
  ],
};
